version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homee
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  app:
    image: node:16
    container_name: app_cont
    restart: always
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: npm run dev

volumes:
  app:
  db:
